### ISSUE TITLE
Unknown word 'use strict'

### ISSUE THREAD

**Issue by BonBonSlick** [minhur/bootstrap-toggle#200]
```
vagrant@qwe:/srv/qwe$ encore dev
Running webpack ...

 ERROR  Failed to compile with 2 errors                                 14:35:45

 error  in ./assets/css/bootstrap-toggle.css

Module build failed: ModuleBuildError: Module build failed: Syntax Error 

(11:3) Unknown word

   9 | 
  10 |  +function ($) {
> 11 |  	'use strict';
     |  	^
  12 | 
  13 | 	// TOGGLE PUBLIC CLASS DEFINITION

    at runLoaders (/srv/q/nowede_modules/webpack/lib/NormalModule.js:195:19)
    at /srv/qwe/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /srv/qwe/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/srv/qwe/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/srv/qwe/node_modules/postcss-loader/lib/index.js:194:44)
    at <anonymous>

 error  in ./node_modules/bootstrap-toggle/js/bootstrap-toggle.js

Module build failed: Syntax Error 

(11:3) Unknown word

   9 | 
  10 |  +function ($) {
> 11 |  	'use strict';
     |  	^
  12 | 
  13 | 	// TOGGLE PUBLIC CLASS DEFINITION


 @ ./node_modules/css-loader??ref--1-2!./node_modules/postcss-loader/lib??ref--1-3!./assets/css/bootstrap-toggle.css 3:10-145
 @ ./assets/css/bootstrap-toggle.css
 @ multi ./assets/css/bootstrap-toggle.css

```

**Comment by rcwoshimao** [comment]
I have the same issue 😭

**Comment by linga66** [comment]
I have same issue 😭😭
